#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
    configure|reconfigure)
        # Do you want /sbin/mount.davfs to be installed SUID root?
        db_input high davfs2/suid_file || true
        db_go || true
    ;;

    *)
        exit 1
    ;;
esac

