#!/bin/sh

set -e
# postinst script for davfs2
. /usr/share/debconf/confmodule

case "$1" in
    configure)
        db_get davfs2/suid_file
	if ! dpkg-statoverride --list /usr/sbin/mount.davfs >/dev/null 2>&1; then
            if [ "$RET" = "true" ]; then
                dpkg-statoverride --update --add root root 4755 \
                    /usr/sbin/mount.davfs > /dev/null 2>&1 || true
            else
                dpkg-statoverride --remove /usr/sbin/mount.davfs \
                    > /dev/null 2>&1 || true
                chmod u-s /usr/sbin/mount.davfs > /dev/null 2>&1 || true 
            fi
        fi

        sys_uid=$(getent passwd davfs2 | cut -d ':' -f 3)
        sys_gid=$(getent group davfs2 | cut -d ':' -f 3)
        if [ "$sys_uid" = "" -a "$sys_gid" = "" ]; then
            adduser --system --home "/var/cache/davfs2" --no-create-home \
                --group davfs2 > /dev/null 2>&1 || true
        elif [ "$sys_uid" = "" ]; then
            adduser --system --home "/var/cache/davfs2" --no-create-home \
                --ingroup davfs2 davfs2 > /dev/null 2>&1 || true
        elif [ "$sys_gid" = "" ]; then
            addgroup --system davfs2 > /dev/null 2>&1 || true
            usermod -g davfs2 davfs2 > /dev/null 2>&1 || true
        fi

        chown root:davfs2 /var/cache/davfs2 > /dev/null 2>&1 || true
        chown root:davfs2 /var/run/mount.davfs > /dev/null 2>&1 || true
        chmod 775 /var/cache/davfs2 > /dev/null 2>&1 || true
        chmod 1775 /var/run/mount.davfs > /dev/null 2>&1 || true

# begin-remove-after: released:forky
# Remove compatibility symlinks installed up until trixie.
    for file in mount.davfs umount.davfs; do
        if [ -L /sbin/$file ]; then
            rm /sbin/$file
        fi
    done
# end-remove-after

    ;;
esac
#DEBHELPER#
